<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://AxisSpring.axis.apache.binildas.com" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://AxisSpring.axis.apache.binildas.com" xmlns:intf="http://AxisSpring.axis.apache.binildas.com" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->

   <wsdl:message name="helloResponse">

      <wsdl:part name="helloReturn" type="soapenc:string"/>

   </wsdl:message>

   <wsdl:message name="helloRequest">

      <wsdl:part name="in0" type="soapenc:string"/>

   </wsdl:message>

   <wsdl:portType name="IHelloWeb">

      <wsdl:operation name="hello" parameterOrder="in0">

         <wsdl:input message="impl:helloRequest" name="helloRequest"/>

         <wsdl:output message="impl:helloResponse" name="helloResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="HelloWebServiceSoapBinding" type="impl:IHelloWeb">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="hello">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="helloRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://AxisSpring.axis.apache.binildas.com" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="helloResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://AxisSpring.axis.apache.binildas.com" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="IHelloWebService">

      <wsdl:port binding="impl:HelloWebServiceSoapBinding" name="HelloWebService">

         <wsdlsoap:address location="http://localhost:8080/AxisSpring/services/HelloWebService"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
